world:
  sv:
    - https://www.svt.se/nyheter/varlden/rss.xml
    - https://www.svd.se/nyheter/utrikes?output=rss
    - https://www.dn.se/rss/utrikes/
    - https://feeds.expressen.se/nyheter/utrikes
  en:
    - https://feeds.bbci.co.uk/news/world/rss.xml
    - https://www.reuters.com/world/rss
    - https://www.theguardian.com/world/rss
    - https://www.euronews.com/rss?level=theme&name=news&theme=world
  de:
    - https://www.tagesschau.de/ausland/index~rss2.xml
    - https://newsfeed.zeit.de/politik/ausland
    - https://www.faz.net/rss/aktuell/politik/ausland/
    - https://www.sueddeutsche.de/contentexport/feed/politik-ausland
    - https://rss.dw.com/rdf/rss-de-welt
  es:
    - https://elpais.com/rss/internacional/portada.xml
    - https://www.elmundo.es/rss/internacional.xml
    - https://www.abc.es/rss/feeds/abc_Internacional.xml
  fr:
    - https://www.lemonde.fr/international/rss_full.xml
    - https://www.francetvinfo.fr/monde.rss
    - https://www.rfi.fr/fr/monde/rss
    - https://www.lefigaro.fr/rss/figaro_international.xml
  el:
    - https://www.kathimerini.gr/world/feed/
    - https://www.tanea.gr/category/world/feed/
    - https://www.tovima.gr/category/world/feed/
