world:
  sv:
    - https://www.svt.se/nyheter/varlden/rss.xml
    - https://www.svd.se/nyheter/utrikes?output=rss
    - https://www.dn.se/rss/utrikes/
    - https://feeds.expressen.se/nyheter/utrikes
