name: Nightly JSON build

on:
  schedule:
    - cron: '0 1 * * *'   # 01:00 UTC = 03:00 Stockholm
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OMP_NUM_THREADS: 1
      TOKENIZERS_PARALLELISM: "false"
      HF_HUB_DISABLE_SYMLINKS_WARNING: "1"

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Show requirements.txt
        run: cat requirements.txt

      - name: Cache Hugging Face models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-hf-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Preload summarization models
        run: |
          python - <<'PY'
          from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
          from transformers import EncoderDecoderModel

          MODELS = [
            "Gabriel/bart-base-cnn-swe",                               # sv
            "facebook/bart-large-cnn",                                  # en
            "Shahm/bart-german",                                        # de
            "moussaKam/barthez-orangesum-abstract",                     # fr
            "Narrativa/bsc_roberta2roberta_shared-mlsum-summarization", # es
            "IMISLab/GreekT5-umt5-base-greeksum",                       # el
          ]

          def preload(m):
            tok = AutoTokenizer.from_pretrained(m, use_fast=False)
            try:
              mdl = AutoModelForSeq2SeqLM.from_pretrained(m)
            except Exception:
              mdl = EncoderDecoderModel.from_pretrained(m)
            pipeline("summarization", model=mdl, tokenizer=tok)
            print("preloaded:", m)

          for m in MODELS:
            preload(m)
          PY

      # Beta-läge: bygg bara 3 kort från senaste 24h
      - name: Run pipeline & export JSON (beta)
        run: TOPN=3 DAYS=1 python make_json.py

      - name: List built files
        run: ls -lh public | sed -n '1,200p'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          publish_dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}
