name: Nightly JSON build

# 03:00 i Stockholm = 01:00 UTC
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:    # gör att du kan klicka “Run workflow” manuellt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # --- Debug: visa exakt requirements.txt som runnern ser ---
      - name: DEBUG – visa requirements.txt
        run: cat requirements.txt

      # --- Installera alla beroenden (inkl. lxml_html_clean) ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # --- Kör pipeline och exportera JSON ---
      - name: Run pipeline & export JSON
        run: python make_json.py

      # --- Publicera till GitHub Pages ---
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          publish_dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}
