name: Nightly JSON build

# 03:00 i Stockholm = 01:00 UTC
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OMP_NUM_THREADS: 1
      TOKENIZERS_PARALLELISM: "false"
      HF_HUB_DISABLE_SYMLINKS_WARNING: "1"

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: DEBUG – visa requirements.txt
        run: cat requirements.txt

      - name: Cache HF models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-hf-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Preload summarizer model
        run: |
          python - <<'PY'
          from transformers import pipeline
          pipeline("summarization", model="csebuetnlp/mT5_multilingual_XLSum")
          print("Models preloaded.")
          PY

      - name: Run pipeline & export JSON
        run: python make_json.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          publish_dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}
