name: Nightly JSON build

# 03:00 i Stockholm = 01:00 UTC (GitHub cron använder UTC-tid)
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:     # gör att du kan klicka "Run workflow" manuellt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Pre-pin lxml 4.9.4
        run: python -m pip install "lxml[html_clean]==4.9.4"

      - name: DEBUG – visa requirements.txt
        run: cat requirements.txt


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt


      - name: Run pipeline & export JSON
        run: python make_json.py

      # ---------- PUBLICERA ----------
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          publish_dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}