name: Nightly JSON build

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OMP_NUM_THREADS: 1
      TOKENIZERS_PARALLELISM: "false"
      HF_HUB_DISABLE_SYMLINKS_WARNING: "1"

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache news NDJSON
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ runner.os }}-news-cache-v1
          restore-keys: |
            ${{ runner.os }}-news-cache-



      - name: Run pipeline & export JSON
        run: KEEP_MODELS_LOADED=0 python make_json.py


      - name: List built files
        run: ls -lh public | sed -n '1,200p'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          publish_dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}
